NET: Add driver for Micrel KS8851
This is an "early access" patch.

Though it "works", it still has many issues that need to be addressed.

This patch will be rebased on a regular basis as it the code is cleaned
up and made to conform to u-boot submission standards.

Signed-off-by: Steve Sakoman <steve@sakoman.com>
[balajitk@ti.com: fix build error and warning
In file included from ks8851.c:28:0:
ks8851.h:37:13: error: conflicting types for 'NetReceive'
u-boot_denx/include/net.h:549:13: note: previous declaration of 'NetReceive' was here
ks8851.c: In function 'ks8851_eth_initialize':
ks8851.c:855:12: warning: assignment from incompatible pointer type
make[1]: *** [ks8851.o] Error 1]
Signed-off-by: Balaji T K <balajitk@ti.com>
[nm@ti.com: some more hacksup and wondering what needs to be done for
CONFIG_KS8851_MLL will need to be enabled.. Anyways.. Sighs and moves on..]
Nyet-Signed-off-by: Nishanth Menon <nm@ti.com>